name: Build APK
on: [push,pull_request]

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build with Buildozer
        run: |
          pip install buildozer
          sudo apt install -y python3-pip python3-setuptools python3-virtualenv git zip unzip openjdk-8-jdk
          buildozer -v android debug
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
